# Form implementation generated from reading ui file 'MainGUI.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QFrame


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 667)
        MainWindow.setStyleSheet("widget_control {\n"
"    background-color: red;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
#         self.widget_control = QtWidgets.QWidget(self.centralwidget)
#         self.widget_control.setMinimumSize(QtCore.QSize(660, 500))
#         self.widget_control.setStyleSheet("QWidget {\n"
# " background-color: rgb(243, 243, 243);\n"
# "}")
#         self.widget_control.setObjectName("widget_control")

        self.tableWidgetMain = QtWidgets.QTableWidget(MainWindow)
        self.tableWidgetMain.setStyleSheet("QTableWidget {\n"
                                          "    background-color: #2596be;\n"
                                          "}")
        self.tableWidgetMain.setObjectName("tableWidgetMain")
        self.tableWidgetMain.setMinimumSize(QtCore.QSize(660, 500))
        self.tableWidgetMain.setMaximumSize(QtCore.QSize(16777215, 16777215))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetMain.sizePolicy().hasHeightForWidth())
        self.tableWidgetMain.setSizePolicy(sizePolicy)
        self.tableWidgetMain.setColumnCount(8)
        self.tableWidgetMain.setRowCount(0)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMain.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMain.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMain.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMain.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMain.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMain.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMain.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMain.setHorizontalHeaderItem(7, item)

        self.tableWidgetMain.horizontalHeader().setDefaultSectionSize(120)
        self.verticalLayout.addWidget(self.tableWidgetMain)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_fb = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fb.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_fb.setObjectName("pushButton_fb")
        self.verticalLayout_2.addWidget(self.pushButton_fb)
        self.pushButton_fb_group = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fb_group.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_fb_group.setObjectName("pushButton_fb_group")
        self.verticalLayout_2.addWidget(self.pushButton_fb_group)
        self.pushButton_fb_post = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fb_post.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_fb_post.setObjectName("pushButton_fb_post")
        self.verticalLayout_2.addWidget(self.pushButton_fb_post)
        self.pushButton_fb_setting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fb_setting.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_fb_setting.setObjectName("pushButton_fb_setting")
        self.verticalLayout_2.addWidget(self.pushButton_fb_setting)

        self.pushButton_fb_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fb_refresh.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_fb_refresh.setObjectName("pushButton_fb_refresh")
        self.verticalLayout_2.addWidget(self.pushButton_fb_refresh)

        self.pushButton_fb_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fb_delete.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_fb_delete.setObjectName("pushButton_fb_delete")
        self.verticalLayout_2.addWidget(self.pushButton_fb_delete)

        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(300, 40))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(83, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_ng_nh_p = QtWidgets.QMenu(self.menubar)
        self.menu_ng_nh_p.setObjectName("menu_ng_nh_p")
        self.menuLi_n_H = QtWidgets.QMenu(self.menubar)
        self.menuLi_n_H.setObjectName("menuLi_n_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_ng_nh_p.menuAction())
        self.menubar.addAction(self.menuLi_n_H.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Marketing Facebook"))
        self.label_2.setText(_translate("MainWindow", "Bảng điều khiển"))
        self.pushButton_fb.setText(_translate("MainWindow", "QL Tài khoản"))
        self.pushButton_fb_group.setText(_translate("MainWindow", "QL Nhóm"))
        self.pushButton_fb_post.setText(_translate("MainWindow", "QL Bài viết"))
        self.pushButton_fb_setting.setText(_translate("MainWindow", "Cấu hình"))
        self.pushButton_fb_refresh.setText(_translate("MainWindow", "Làm mới"))
        self.pushButton_fb_delete.setText(_translate("MainWindow", "Xóa"))

        self.label.setText(_translate("MainWindow", "ho tro ki thuat"))
        self.menu_ng_nh_p.setTitle(_translate("MainWindow", "Đăng nhập"))
        self.menuLi_n_H.setTitle(_translate("MainWindow", "Liên Hệ"))

        item = self.tableWidgetMain.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_fb", "id"))
        item = self.tableWidgetMain.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_fb", "FB ID"))
        item = self.tableWidgetMain.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_fb", "Run"))
        item = self.tableWidgetMain.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_fb", "Pause"))
        item = self.tableWidgetMain.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_fb", "Stop"))
        item = self.tableWidgetMain.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Result"))
        item = self.tableWidgetMain.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Fb Name"))
        item = self.tableWidgetMain.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Action"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
