# Form implementation generated from reading ui file 'MainProUI.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 568)
        MainWindow.setStyleSheet("#menubar {\n"
"    background-color: rgb(46, 52, 54);\n"
"color: #fff;\n"
"padding: 6px 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
                "padding: 0;\n"
                "margin: 0;\n"
                "border: none;\n"
                "color: #fff;\n"
                "}\n"
                "#widgetLeftContainer {\n"
                "    background-color: #1f232a;\n"
                "    color: #343a40;\n"
                "padding-right: 5px;"
                "}\n"
                "#centralwidget {\n"
                "background-color: #2c313c;\n"
                "}\n"
                "#widgetBodyContainer {\n"
                "    background-color: #495057;\n"
                "}\n"               
                "QToolButton {\n"
                "\n"
                "padding: 5px 10px;\n"
                "text-align: left;\n"
                "padding: 5px 10px;\n"
                "border-radius: 10px;\n"
                "}\n"
             """QToolButton:hover {
             background-color: #495057;
             }
             QCheckBox::indicator
{
background-color : lightgreen;
}"""
      )
        """
        QPushButton {
                      background-color:  #495057;
                      color: #FFFFFF;
                      border-style: outset;
                      padding: 2px 10px;
                      border-width: 1px;
                      border-radius: 10px;
                      border-color: #2c313c;
                      min-width: 5em;
                  }
                  QPushButton:hover {
                       background-color: #2c313c;
                       color: #FFFFFF;
                      }
                  QPushButton:pressed {
                      background-color: white;
                      color: black;
                      }                      
                      """
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetLeftContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetLeftContainer.sizePolicy().hasHeightForWidth())
        self.widgetLeftContainer.setSizePolicy(sizePolicy)
        self.widgetLeftContainer.setObjectName("widgetLeftContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetLeftContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetSubLeft = QtWidgets.QWidget(self.widgetLeftContainer)
        self.widgetSubLeft.setObjectName("widgetSubLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widgetSubLeft)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameControl = QtWidgets.QFrame(self.widgetSubLeft)
        self.frameControl.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameControl.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameControl.setObjectName("frameControl")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameControl)
        self.verticalLayout_3.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolButton_account = QtWidgets.QToolButton(self.frameControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_account.sizePolicy().hasHeightForWidth())
        self.toolButton_account.setSizePolicy(sizePolicy)
        self.toolButton_account.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./svg_icon/icons/facebook.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_account.setIcon(icon)
        self.toolButton_account.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_account.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_account.setObjectName("toolButton_account")
        self.verticalLayout_3.addWidget(self.toolButton_account)
        self.toolButton_group = QtWidgets.QToolButton(self.frameControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_group.sizePolicy().hasHeightForWidth())
        self.toolButton_group.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./svg_icon/icons/user-plus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_group.setIcon(icon1)
        self.toolButton_group.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_group.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_group.setObjectName("toolButton_group")
        self.verticalLayout_3.addWidget(self.toolButton_group)
        self.toolButton_posts = QtWidgets.QToolButton(self.frameControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_posts.sizePolicy().hasHeightForWidth())
        self.toolButton_posts.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./svg_icon/icons/file.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_posts.setIcon(icon2)
        self.toolButton_posts.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_posts.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_posts.setObjectName("toolButton_posts")
        self.verticalLayout_3.addWidget(self.toolButton_posts)
        self.verticalLayout_2.addWidget(self.frameControl, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.widgetSubLeft)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolButton_add = QtWidgets.QToolButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_add.sizePolicy().hasHeightForWidth())
        self.toolButton_add.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./svg_icon/icons/plus-square.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_add.setIcon(icon3)
        self.toolButton_add.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_add.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_add.setObjectName("toolButton_add")
        self.verticalLayout_4.addWidget(self.toolButton_add)
        self.toolButton_edit = QtWidgets.QToolButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_edit.sizePolicy().hasHeightForWidth())
        self.toolButton_edit.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./svg_icon/icons/edit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_edit.setIcon(icon4)
        self.toolButton_edit.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_edit.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_edit.setObjectName("toolButton_edit")
        self.verticalLayout_4.addWidget(self.toolButton_edit)
        self.toolButton_delete = QtWidgets.QToolButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_delete.sizePolicy().hasHeightForWidth())
        self.toolButton_delete.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./svg_icon/icons/delete.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_delete.setIcon(icon5)
        self.toolButton_delete.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_delete.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_delete.setObjectName("toolButton_delete")
        self.verticalLayout_4.addWidget(self.toolButton_delete)
        self.toolButton_view = QtWidgets.QToolButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_view.sizePolicy().hasHeightForWidth())
        self.toolButton_view.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./svg_icon/icons/file-text.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_view.setIcon(icon6)
        self.toolButton_view.setIconSize(QtCore.QSize(24, 24))
        self.toolButton_view.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_view.setObjectName("toolButton_view")
        self.verticalLayout_4.addWidget(self.toolButton_view)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addWidget(self.widgetSubLeft)
        self.horizontalLayout.addWidget(self.widgetLeftContainer, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.widgetBodyContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetBodyContainer.sizePolicy().hasHeightForWidth())
        self.widgetBodyContainer.setSizePolicy(sizePolicy)
        self.widgetBodyContainer.setMinimumSize(QtCore.QSize(500, 0))
        self.widgetBodyContainer.setObjectName("widgetBodyContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widgetBodyContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widgetHeader = QtWidgets.QWidget(self.widgetBodyContainer)
        self.widgetHeader.setObjectName("widgetHeader")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetHeader)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.widgetHeader)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_5.addWidget(self.widgetHeader, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widgetMain = QtWidgets.QWidget(self.widgetBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetMain.sizePolicy().hasHeightForWidth())
        self.widgetMain.setSizePolicy(sizePolicy)
        self.widgetMain.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetMain.setObjectName("widgetMain")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widgetMain)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.widgetMain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(100)
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: #343a40;")
        self.tableWidget.setShowGrid(True)
        # self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_5.addWidget(self.widgetMain)
        self.widgetFooter = QtWidgets.QWidget(self.widgetBodyContainer)
        self.widgetFooter.setMaximumSize(QtCore.QSize(16777215, 46))
        self.widgetFooter.setObjectName("widgetFooter")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widgetFooter)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widgetFooter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.widgetFooter, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout.addWidget(self.widgetBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 35))
        self.menubar.setObjectName("menubar")
        self.menu_ng_nh_p = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.NoAntialias)
        self.menu_ng_nh_p.setFont(font)
        self.menu_ng_nh_p.setMouseTracking(True)
        self.menu_ng_nh_p.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.menu_ng_nh_p.setAcceptDrops(False)
        self.menu_ng_nh_p.setObjectName("menu_ng_nh_p")
        self.menuLi_n_h = QtWidgets.QMenu(self.menubar)
        self.menuLi_n_h.setMouseTracking(True)
        self.menuLi_n_h.setAcceptDrops(False)
        self.menuLi_n_h.setObjectName("menuLi_n_h")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu_ng_nh_p.menuAction())
        self.menubar.addAction(self.menuLi_n_h.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FaceBook Marketing"))
        self.toolButton_account.setText(_translate("MainWindow", " QL Tài Khoản"))
        self.toolButton_group.setText(_translate("MainWindow", " QL Nhóm"))
        self.toolButton_posts.setText(_translate("MainWindow", " QL Bài Viết"))
        self.toolButton_add.setText(_translate("MainWindow", " Thêm"))
        self.toolButton_edit.setText(_translate("MainWindow", " Sửa"))
        self.toolButton_delete.setText(_translate("MainWindow", " Xóa"))
        self.toolButton_view.setText(_translate("MainWindow", " Xem Danh Sách"))
        self.label.setText(_translate("MainWindow", "BẢNG ĐIỀU KHIỂN"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FB ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FB NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RUN"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PAUSE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "TOP"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "RESULT"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "ACTION"))
        self.label_2.setText(_translate("MainWindow", "Author: Phâm mền auto"))
        self.menu_ng_nh_p.setTitle(_translate("MainWindow", "Đăng nhập"))
        self.menuLi_n_h.setTitle(_translate("MainWindow", "Liên hệ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
