# Form implementation generated from reading ui file 'AddAccountGui.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QWidget, QFileDialog
from PyQt6.QtCore import QCoreApplication



class Ui_Dialog_Add_Account():
    # def __init__(self, database, data=None):
    #     super().__init__()
    #
    #     self.database = database
    #     self.data = data
    #     self.dialog = None

    def setupUi(self, Dialog_Add_Account):
        self.dialog = Dialog_Add_Account
        Dialog_Add_Account.setObjectName("Dialog_Add_Account")
        Dialog_Add_Account.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Add_Account)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_uid = QtWidgets.QLineEdit(Dialog_Add_Account)
        self.lineEdit_uid.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_uid.setObjectName("lineEdit_uid")
        self.verticalLayout.addWidget(self.lineEdit_uid)
        self.lineEdit_name = QtWidgets.QLineEdit(Dialog_Add_Account)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.lineEdit_pass = QtWidgets.QLineEdit(Dialog_Add_Account)
        self.lineEdit_pass.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.verticalLayout.addWidget(self.lineEdit_pass)
        self.lineEdit_cookie = QtWidgets.QLineEdit(Dialog_Add_Account)
        self.lineEdit_cookie.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_cookie.setObjectName("lineEdit_cookie")
        self.verticalLayout.addWidget(self.lineEdit_cookie)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_profile = QtWidgets.QLineEdit(Dialog_Add_Account)
        self.lineEdit_profile.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_profile.setObjectName("lineEdit_profile")
        self.horizontalLayout.addWidget(self.lineEdit_profile)
        self.toolButton_path = QtWidgets.QToolButton(Dialog_Add_Account)
        self.toolButton_path.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_path.setObjectName("toolButton_path")

        # self.toolButton_path.clicked.connect(self.folder_open)
        self.horizontalLayout.addWidget(self.toolButton_path)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_result = QtWidgets.QLabel(Dialog_Add_Account)
        self.label_result.setMinimumSize(QtCore.QSize(0, 40))
        self.label_result.setText("")
        self.label_result.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_Add_Account)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        # self.pushButton_cancel.clicked.connect(self.close_dialog)
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.pushButton_add = QtWidgets.QPushButton(Dialog_Add_Account)
        self.pushButton_add.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_add.setObjectName("pushButton_add")

        # self.pushButton_add.clicked.connect(self.add_account)
        self.horizontalLayout_2.addWidget(self.pushButton_add)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_Add_Account)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Add_Account)

        # if self.data:
        #     self.render_edit()
        #     self.pushButton_add.setText("Sửa")

    def retranslateUi(self, Dialog_Add_Account):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Add_Account.setWindowTitle(_translate("Dialog_Add_Account", "Thêm Tài KHoản Facebook"))
        self.lineEdit_uid.setPlaceholderText(_translate("Dialog_Add_Account", "UID"))
        self.lineEdit_name.setPlaceholderText(_translate("Dialog_Add_Account", "Name Facbook"))
        self.lineEdit_pass.setPlaceholderText(_translate("Dialog_Add_Account", "Pass Word"))
        self.lineEdit_cookie.setPlaceholderText(_translate("Dialog_Add_Account", "Cookie"))
        self.lineEdit_profile.setPlaceholderText(_translate("Dialog_Add_Account", "Đường dẫn profile"))
        self.toolButton_path.setText(_translate("Dialog_Add_Account", "..."))
        self.pushButton_cancel.setText(_translate("Dialog_Add_Account", "Hủy"))
        self.pushButton_add.setText(_translate("Dialog_Add_Account", "Thêm"))






# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog_Add_Account = QtWidgets.QDialog()
#     ui = Ui_Dialog_Add_Account()
#     ui.setupUi(Dialog_Add_Account)
#     Dialog_Add_Account.show()
#     sys.exit(app.exec())
