# Form implementation generated from reading ui file 'AddPostGui.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_DialogAddPost(QtWidgets.QDialog):
    # def __init__(self, database, post=""):
    #     super().__init__()
    #     self.database = database
    #     self.post = post

    def setupUi(self, DialogAddPost):
        self.dialog = DialogAddPost
        DialogAddPost.setObjectName("DialogAddPost")
        DialogAddPost.resize(500, 400)
        DialogAddPost.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogAddPost)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_title = QtWidgets.QLineEdit(DialogAddPost)
        self.lineEdit_title.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.verticalLayout.addWidget(self.lineEdit_title)
        self.textEdit_des = QtWidgets.QTextEdit(DialogAddPost)
        self.textEdit_des.setMinimumSize(QtCore.QSize(0, 200))
        self.textEdit_des.setObjectName("textEdit_des")
        self.verticalLayout.addWidget(self.textEdit_des)
        self.textEdit_note = QtWidgets.QTextEdit(DialogAddPost)
        self.textEdit_note.setObjectName("textEdit_note")
        self.verticalLayout.addWidget(self.textEdit_note)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_img = QtWidgets.QLineEdit(DialogAddPost)
        self.lineEdit_img.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_img.setObjectName("lineEdit_img")
        self.horizontalLayout_2.addWidget(self.lineEdit_img)
        self.toolButton_img = QtWidgets.QToolButton(DialogAddPost)
        self.toolButton_img.setMinimumSize(QtCore.QSize(35, 35))
        self.toolButton_img.setObjectName("toolButton_img")

        # self.toolButton_img.clicked.connect(self.open_img)
        self.horizontalLayout_2.addWidget(self.toolButton_img)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton = QtWidgets.QToolButton(DialogAddPost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMinimumSize(QtCore.QSize(0, 35))
        self.toolButton.setObjectName("toolButton")

        # self.toolButton.clicked.connect(self.close_dialog)
        self.horizontalLayout.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(DialogAddPost)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(0, 35))
        self.toolButton_2.setObjectName("toolButton_2")

        # if self.post:
        #     self.toolButton_2.setText("Sửa")
        #     self.render_post_edit()
        #     self.toolButton_2.clicked.connect(self.edit_post)
        # else:
        #     self.toolButton_2.setText("Thêm")
        #     self.toolButton_2.clicked.connect(self.add_post_new)

        self.horizontalLayout.addWidget(self.toolButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogAddPost)
        QtCore.QMetaObject.connectSlotsByName(DialogAddPost)

    def retranslateUi(self, DialogAddPost):
        _translate = QtCore.QCoreApplication.translate
        DialogAddPost.setWindowTitle(_translate("DialogAddPost", "Thêm bài viết mới"))
        self.lineEdit_title.setPlaceholderText(_translate("DialogAddPost", "Tiêu đề bài viết"))
        self.textEdit_des.setPlaceholderText(_translate("DialogAddPost", "Nội dung bài viết"))
        self.textEdit_note.setPlaceholderText(_translate("DialogAddPost", "Ghi chú"))
        self.lineEdit_img.setPlaceholderText(_translate("DialogAddPost", "Đường dẫn hình ảnh"))
        self.toolButton_img.setText(_translate("DialogAddPost", "..."))
        self.toolButton.setText(_translate("DialogAddPost", "Hủy"))


    # def close_dialog(self):
    #     self.dialog.close()
    #
    # def add_post_new(self):
    #     title = self.lineEdit_title.text()
    #     description = self.textEdit_des.toPlainText()
    #     note = self.textEdit_note.toPlainText()
    #     img_path = self.lineEdit_img.text()
    #
    #     message = self.database.insert_table_post(title, description, img_path, note)
    #     QtWidgets.QMessageBox.about(self, "Save post", message)
    #
    # def open_img(self):
    #     file_name = QFileDialog.getOpenFileNames(self, "Open File Img", filter='img_files(*jpg *jpeg *png)',
    #                                              options=QFileDialog.Option.DontUseNativeDialog)
    #
    #     if file_name[0]:
    #         self.lineEdit_img.setText(','.join(file_name[0]))
    #
    # def render_post_edit(self):
    #     if self.post:
    #         self.lineEdit_title.setText(self.post[1])
    #         self.textEdit_des.setText(self.post[2])
    #         self.lineEdit_img.setText(self.post[3])
    #         self.textEdit_note.setText(self.post[4])
    #
    # def edit_post(self):
    #     title = self.lineEdit_title.text()
    #     description = self.textEdit_des.toPlainText()
    #     note = self.textEdit_note.toPlainText()
    #     img_path = self.lineEdit_img.text()
    #
    #     message = self.database.update_table_post(self.post[0], title, description, note, img_path)
    #     QtWidgets.QMessageBox.about(self, "Edit Post", message)



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     DialogAddPost = QtWidgets.QDialog()
#     ui = Ui_DialogAddPost()
#     ui.setupUi(DialogAddPost)
#     DialogAddPost.show()
#     sys.exit(app.exec())
